language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: LcFtkik5ZVtWDtRr681j4zl7wZ7zb/KVVHEG7K7/r2Eut5w4rE+iWw3np0NXfW39kcJv0LRxp+WRtcBMOlN68LOTmineB6VW54F03mJorASg1kGAnjsQDq0m45nGH+b5R0s+4QhGQdx6mF57IpOfB8cdsdjplCYyNCQqCkOMI9bStrNOCHAuIvn6Njf0VB7b2ul43IImxkpPlKAJYaQtiW0NlBZ88C2oxmCOXoJL3Bl/nAOyUpzIiinmJSwnqMWni7lpOtIl52HVfkVFXctQcjif6brTlb62BcIVMtdeXtCsBuAI8xNqUmjuhbfzmlW6tdlYh5iibePrdXRvG8NnhU+sJGtBk4E+3U18FDLHH43pHvTAfCYDDbXqo+2lxySw7vkF3K8Ri3NnXt4ensvBg3oiH+Eeh69/CThXkvkpsgykLzgaRBrtodemGFyumhXB4GCbN9seUS99gom+aR6fL/nSgziS0xxbPw1STGbVBFehMjlKEC/baxZ01IDlp4sfJUQRQXZIqs5Tqkt/Nt0gReRJOYnnC9c1YdEXH5doLrpYqTk9RlZbELbsg20Sagmp1WWXF3jpjOpZ3jEzZEhVaMzTOODfoe2A+m/Qdpi/MrAEl9obK7Nv4PI9o1rdh+ZtBnEpl3EXqOGobUDA/q7uR2ZzX+5gqzeStJZwHy7HH5E=
